### ISSUE TITLE
Annotation for stratified sampling based on event status

### ISSUE THREAD

**Issue by hfrick** [hfrick/tidymodels-survival-workshop#10]
> Should we mention that, if we don't make the Surv object at first, we could use the event indicator for stratification then make the surv object later? 
> 
> We could put something in the annotations with a recipe that would remove/change roles of the original columns used to make the Surv object?

_Originally posted by @topepo in https://github.com/hfrick/tidymodels-survival-workshop/pull/6#discussion_r1651126589_

**Comment by topepo** [comment]
Closed by b50d59a ([this line](https://github.com/hfrick/tidymodels-survival-workshop/commit/b50d59adadf883a02a69eb3142179e59fde0a996#diff-eab99e842e3590ea27d0e153046c4a1d5ec962812613c513f15c5f4513962d4dR232))
